sudo: false
language: ruby
rvm: 2.0.0
addons:
  apt:
    packages:
      - debconf
install:
  - pip install --user six requests
  - git clone --depth 1 -b r2.20-1 git://github.com/rhinstaller/pykickstart.git
  - (cd pykickstart && pip install --user .)
  - bundle install --jobs=3 --retry=3
